// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=ts"
// @generated from file qdrant_internal_service.proto (package qdrant, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HttpPortRequest, HttpPortResponse } from "./qdrant_internal_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service qdrant.QdrantInternal
 */
export const QdrantInternal = {
  typeName: "qdrant.QdrantInternal",
  methods: {
    /**
     *
     * Get HTTP port for remote host.
     *
     * @generated from rpc qdrant.QdrantInternal.GetHttpPort
     */
    getHttpPort: {
      name: "GetHttpPort",
      I: HttpPortRequest,
      O: HttpPortResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

