// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=js"
// @generated from file qdrant.proto (package qdrant, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_collections_service } from "./collections_service_pb.js";
import { file_points_service } from "./points_service_pb.js";
import { file_snapshots_service } from "./snapshots_service_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file qdrant.proto.
 */
export const file_qdrant: GenFile = /*@__PURE__*/
  fileDesc("CgxxZHJhbnQucHJvdG8SBnFkcmFudCIUChJIZWFsdGhDaGVja1JlcXVlc3QiUgoQSGVhbHRoQ2hlY2tSZXBseRINCgV0aXRsZRgBIAEoCRIPCgd2ZXJzaW9uGAIgASgJEhMKBmNvbW1pdBgDIAEoCUgAiAEBQgkKB19jb21taXQyTwoGUWRyYW50EkUKC0hlYWx0aENoZWNrEhoucWRyYW50LkhlYWx0aENoZWNrUmVxdWVzdBoYLnFkcmFudC5IZWFsdGhDaGVja1JlcGx5IgBCFaoCElFkcmFudC5DbGllbnQuR3JwY2IGcHJvdG8z", [file_collections_service, file_points_service, file_snapshots_service]);

/**
 * @generated from message qdrant.HealthCheckRequest
 */
export type HealthCheckRequest = Message<"qdrant.HealthCheckRequest"> & {
};

/**
 * Describes the message qdrant.HealthCheckRequest.
 * Use `create(HealthCheckRequestSchema)` to create a new message.
 */
export const HealthCheckRequestSchema: GenMessage<HealthCheckRequest> = /*@__PURE__*/
  messageDesc(file_qdrant, 0);

/**
 * @generated from message qdrant.HealthCheckReply
 */
export type HealthCheckReply = Message<"qdrant.HealthCheckReply"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * @generated from field: optional string commit = 3;
   */
  commit?: string;
};

/**
 * Describes the message qdrant.HealthCheckReply.
 * Use `create(HealthCheckReplySchema)` to create a new message.
 */
export const HealthCheckReplySchema: GenMessage<HealthCheckReply> = /*@__PURE__*/
  messageDesc(file_qdrant, 1);

/**
 * @generated from service qdrant.Qdrant
 */
export const Qdrant: GenService<{
  /**
   * @generated from rpc qdrant.Qdrant.HealthCheck
   */
  healthCheck: {
    methodKind: "unary";
    input: typeof HealthCheckRequestSchema;
    output: typeof HealthCheckReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_qdrant, 0);

