// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=js"
// @generated from file snapshots_service.proto (package qdrant, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file snapshots_service.proto.
 */
export const file_snapshots_service: GenFile = /*@__PURE__*/
  fileDesc("ChdzbmFwc2hvdHNfc2VydmljZS5wcm90bxIGcWRyYW50IhsKGUNyZWF0ZUZ1bGxTbmFwc2hvdFJlcXVlc3QiGgoYTGlzdEZ1bGxTbmFwc2hvdHNSZXF1ZXN0IjIKGURlbGV0ZUZ1bGxTbmFwc2hvdFJlcXVlc3QSFQoNc25hcHNob3RfbmFtZRgBIAEoCSIwChVDcmVhdGVTbmFwc2hvdFJlcXVlc3QSFwoPY29sbGVjdGlvbl9uYW1lGAEgASgJIi8KFExpc3RTbmFwc2hvdHNSZXF1ZXN0EhcKD2NvbGxlY3Rpb25fbmFtZRgBIAEoCSJHChVEZWxldGVTbmFwc2hvdFJlcXVlc3QSFwoPY29sbGVjdGlvbl9uYW1lGAEgASgJEhUKDXNuYXBzaG90X25hbWUYAiABKAkiiAEKE1NuYXBzaG90RGVzY3JpcHRpb24SDAoEbmFtZRgBIAEoCRIxCg1jcmVhdGlvbl90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIMCgRzaXplGAMgASgDEhUKCGNoZWNrc3VtGAQgASgJSACIAQFCCwoJX2NoZWNrc3VtImEKFkNyZWF0ZVNuYXBzaG90UmVzcG9uc2USOQoUc25hcHNob3RfZGVzY3JpcHRpb24YASABKAsyGy5xZHJhbnQuU25hcHNob3REZXNjcmlwdGlvbhIMCgR0aW1lGAIgASgBImEKFUxpc3RTbmFwc2hvdHNSZXNwb25zZRI6ChVzbmFwc2hvdF9kZXNjcmlwdGlvbnMYASADKAsyGy5xZHJhbnQuU25hcHNob3REZXNjcmlwdGlvbhIMCgR0aW1lGAIgASgBIiYKFkRlbGV0ZVNuYXBzaG90UmVzcG9uc2USDAoEdGltZRgBIAEoATLdAwoJU25hcHNob3RzEkkKBkNyZWF0ZRIdLnFkcmFudC5DcmVhdGVTbmFwc2hvdFJlcXVlc3QaHi5xZHJhbnQuQ3JlYXRlU25hcHNob3RSZXNwb25zZSIAEkUKBExpc3QSHC5xZHJhbnQuTGlzdFNuYXBzaG90c1JlcXVlc3QaHS5xZHJhbnQuTGlzdFNuYXBzaG90c1Jlc3BvbnNlIgASSQoGRGVsZXRlEh0ucWRyYW50LkRlbGV0ZVNuYXBzaG90UmVxdWVzdBoeLnFkcmFudC5EZWxldGVTbmFwc2hvdFJlc3BvbnNlIgASUQoKQ3JlYXRlRnVsbBIhLnFkcmFudC5DcmVhdGVGdWxsU25hcHNob3RSZXF1ZXN0Gh4ucWRyYW50LkNyZWF0ZVNuYXBzaG90UmVzcG9uc2UiABJNCghMaXN0RnVsbBIgLnFkcmFudC5MaXN0RnVsbFNuYXBzaG90c1JlcXVlc3QaHS5xZHJhbnQuTGlzdFNuYXBzaG90c1Jlc3BvbnNlIgASUQoKRGVsZXRlRnVsbBIhLnFkcmFudC5EZWxldGVGdWxsU25hcHNob3RSZXF1ZXN0Gh4ucWRyYW50LkRlbGV0ZVNuYXBzaG90UmVzcG9uc2UiAEIVqgISUWRyYW50LkNsaWVudC5HcnBjYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message qdrant.CreateFullSnapshotRequest
 */
export type CreateFullSnapshotRequest = Message<"qdrant.CreateFullSnapshotRequest"> & {
};

/**
 * Describes the message qdrant.CreateFullSnapshotRequest.
 * Use `create(CreateFullSnapshotRequestSchema)` to create a new message.
 */
export const CreateFullSnapshotRequestSchema: GenMessage<CreateFullSnapshotRequest> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 0);

/**
 * @generated from message qdrant.ListFullSnapshotsRequest
 */
export type ListFullSnapshotsRequest = Message<"qdrant.ListFullSnapshotsRequest"> & {
};

/**
 * Describes the message qdrant.ListFullSnapshotsRequest.
 * Use `create(ListFullSnapshotsRequestSchema)` to create a new message.
 */
export const ListFullSnapshotsRequestSchema: GenMessage<ListFullSnapshotsRequest> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 1);

/**
 * @generated from message qdrant.DeleteFullSnapshotRequest
 */
export type DeleteFullSnapshotRequest = Message<"qdrant.DeleteFullSnapshotRequest"> & {
  /**
   * Name of the full snapshot
   *
   * @generated from field: string snapshot_name = 1;
   */
  snapshotName: string;
};

/**
 * Describes the message qdrant.DeleteFullSnapshotRequest.
 * Use `create(DeleteFullSnapshotRequestSchema)` to create a new message.
 */
export const DeleteFullSnapshotRequestSchema: GenMessage<DeleteFullSnapshotRequest> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 2);

/**
 * @generated from message qdrant.CreateSnapshotRequest
 */
export type CreateSnapshotRequest = Message<"qdrant.CreateSnapshotRequest"> & {
  /**
   * Name of the collection
   *
   * @generated from field: string collection_name = 1;
   */
  collectionName: string;
};

/**
 * Describes the message qdrant.CreateSnapshotRequest.
 * Use `create(CreateSnapshotRequestSchema)` to create a new message.
 */
export const CreateSnapshotRequestSchema: GenMessage<CreateSnapshotRequest> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 3);

/**
 * @generated from message qdrant.ListSnapshotsRequest
 */
export type ListSnapshotsRequest = Message<"qdrant.ListSnapshotsRequest"> & {
  /**
   * Name of the collection
   *
   * @generated from field: string collection_name = 1;
   */
  collectionName: string;
};

/**
 * Describes the message qdrant.ListSnapshotsRequest.
 * Use `create(ListSnapshotsRequestSchema)` to create a new message.
 */
export const ListSnapshotsRequestSchema: GenMessage<ListSnapshotsRequest> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 4);

/**
 * @generated from message qdrant.DeleteSnapshotRequest
 */
export type DeleteSnapshotRequest = Message<"qdrant.DeleteSnapshotRequest"> & {
  /**
   * Name of the collection
   *
   * @generated from field: string collection_name = 1;
   */
  collectionName: string;

  /**
   * Name of the collection snapshot
   *
   * @generated from field: string snapshot_name = 2;
   */
  snapshotName: string;
};

/**
 * Describes the message qdrant.DeleteSnapshotRequest.
 * Use `create(DeleteSnapshotRequestSchema)` to create a new message.
 */
export const DeleteSnapshotRequestSchema: GenMessage<DeleteSnapshotRequest> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 5);

/**
 * @generated from message qdrant.SnapshotDescription
 */
export type SnapshotDescription = Message<"qdrant.SnapshotDescription"> & {
  /**
   * Name of the snapshot
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Creation time of the snapshot
   *
   * @generated from field: google.protobuf.Timestamp creation_time = 2;
   */
  creationTime?: Timestamp;

  /**
   * Size of the snapshot in bytes
   *
   * @generated from field: int64 size = 3;
   */
  size: bigint;

  /**
   * SHA256 digest of the snapshot file
   *
   * @generated from field: optional string checksum = 4;
   */
  checksum?: string;
};

/**
 * Describes the message qdrant.SnapshotDescription.
 * Use `create(SnapshotDescriptionSchema)` to create a new message.
 */
export const SnapshotDescriptionSchema: GenMessage<SnapshotDescription> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 6);

/**
 * @generated from message qdrant.CreateSnapshotResponse
 */
export type CreateSnapshotResponse = Message<"qdrant.CreateSnapshotResponse"> & {
  /**
   * @generated from field: qdrant.SnapshotDescription snapshot_description = 1;
   */
  snapshotDescription?: SnapshotDescription;

  /**
   * Time spent to process
   *
   * @generated from field: double time = 2;
   */
  time: number;
};

/**
 * Describes the message qdrant.CreateSnapshotResponse.
 * Use `create(CreateSnapshotResponseSchema)` to create a new message.
 */
export const CreateSnapshotResponseSchema: GenMessage<CreateSnapshotResponse> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 7);

/**
 * @generated from message qdrant.ListSnapshotsResponse
 */
export type ListSnapshotsResponse = Message<"qdrant.ListSnapshotsResponse"> & {
  /**
   * @generated from field: repeated qdrant.SnapshotDescription snapshot_descriptions = 1;
   */
  snapshotDescriptions: SnapshotDescription[];

  /**
   * Time spent to process
   *
   * @generated from field: double time = 2;
   */
  time: number;
};

/**
 * Describes the message qdrant.ListSnapshotsResponse.
 * Use `create(ListSnapshotsResponseSchema)` to create a new message.
 */
export const ListSnapshotsResponseSchema: GenMessage<ListSnapshotsResponse> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 8);

/**
 * @generated from message qdrant.DeleteSnapshotResponse
 */
export type DeleteSnapshotResponse = Message<"qdrant.DeleteSnapshotResponse"> & {
  /**
   * Time spent to process
   *
   * @generated from field: double time = 1;
   */
  time: number;
};

/**
 * Describes the message qdrant.DeleteSnapshotResponse.
 * Use `create(DeleteSnapshotResponseSchema)` to create a new message.
 */
export const DeleteSnapshotResponseSchema: GenMessage<DeleteSnapshotResponse> = /*@__PURE__*/
  messageDesc(file_snapshots_service, 9);

/**
 * @generated from service qdrant.Snapshots
 */
export const Snapshots: GenService<{
  /**
   * Create collection snapshot
   *
   * @generated from rpc qdrant.Snapshots.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateSnapshotRequestSchema;
    output: typeof CreateSnapshotResponseSchema;
  },
  /**
   * List collection snapshots
   *
   * @generated from rpc qdrant.Snapshots.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListSnapshotsRequestSchema;
    output: typeof ListSnapshotsResponseSchema;
  },
  /**
   * Delete collection snapshot
   *
   * @generated from rpc qdrant.Snapshots.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteSnapshotRequestSchema;
    output: typeof DeleteSnapshotResponseSchema;
  },
  /**
   * Create full storage snapshot
   *
   * @generated from rpc qdrant.Snapshots.CreateFull
   */
  createFull: {
    methodKind: "unary";
    input: typeof CreateFullSnapshotRequestSchema;
    output: typeof CreateSnapshotResponseSchema;
  },
  /**
   * List full storage snapshots
   *
   * @generated from rpc qdrant.Snapshots.ListFull
   */
  listFull: {
    methodKind: "unary";
    input: typeof ListFullSnapshotsRequestSchema;
    output: typeof ListSnapshotsResponseSchema;
  },
  /**
   * Delete full storage snapshot
   *
   * @generated from rpc qdrant.Snapshots.DeleteFull
   */
  deleteFull: {
    methodKind: "unary";
    input: typeof DeleteFullSnapshotRequestSchema;
    output: typeof DeleteSnapshotResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_snapshots_service, 0);

