name: Pull request

on:
  pull_request:
    branches: [master]

jobs:
  precheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 21]
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
        with:
          version: 9.15.9
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          scope: "@qdrant"
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Node packages audit
        run: pnpm audit --prod

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          CI: 1

      - name: Project checks
        run: pnpm -r pre-check

      - name: Integration tests
        run: packages/qdrant-js/scripts/integration-tests.sh
        shell: bash
