name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for provenance statement
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
        with:
          version: 9.15.9
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          scope: "@qdrant"
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Node packages audit
        run: pnpm audit --prod

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        env:
          CI: 1

      - name: Add registry path to .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: node scripts/prepublish.mjs
      - run: pnpm publish --provenance --no-git-checks --filter '!monorepo'

      - name: Archive npm failure logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ failure() }}
        with:
          name: npm-logs
          path: ~/.npm/_logs
          retention-days: 30
